### ISSUE TITLE
Dimension mismatch problem

### ISSUE THREAD

**Issue by Gavin-Evans** [tengteng95/Pose-Transfer#28]
Hi,
I have a problem in training on deepfashion

error as follows:

`Traceback (most recent call last):
  File "train.py", line 27, in <module>
    model.optimize_parameters()
  File "/home/hyw/zp/pytorch/Pose-Transfer-master/models/PATN.py", line 221, in optimize_parameters
    self.forward()
  File "/home/hyw/zp/pytorch/Pose-Transfer-master/models/PATN.py", line 125, in forward
    self.fake_p2 = self.netG(G_input)
  File "/home/hyw/zp/Anaconda2_pytorch_keras/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyw/zp/pytorch/Pose-Transfer-master/models/model_variants.py", line 165, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/hyw/zp/Anaconda2_pytorch_keras/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 204, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/hyw/zp/Anaconda2_pytorch_keras/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyw/zp/pytorch/Pose-Transfer-master/models/model_variants.py", line 148, in forward
    x1, x2, _ = model(x1, x2)
  File "/home/hyw/zp/Anaconda2_pytorch_keras/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyw/zp/pytorch/Pose-Transfer-master/models/model_variants.py", line 63, in forward
    x1_out = x1_out * att
RuntimeError: The size of tensor a (188) must match the size of tensor b (44) at non-singleton dimension 3
`
Can you explain how I should deal with this problem? please

thanks  a lot

**Comment by ysl1402** [comment]
Maybe you forgot to crop the images into 256*176.

**Comment by Gavin-Evans** [comment]
> Maybe you forgot to crop the images into 256*176.

thank you, however ,I would like to get something else, deepfashion have 2 versions one is old (where all the images have the resolution 256x256) ,another one is HD(1101X750),which one do you use?

**Comment by jessemelpolio** [comment]
We use the 256x256 version, but in order to save computation, we center cropped the images to the size of 256x176, because the boundary portions are not relevant to the person image generation.

**Comment by Gavin-Evans** [comment]
> We use the 256x256 version, but in order to save computation, we center cropped the images to the size of 256x176, because the boundary portions are not relevant to the person image generation.

ok, thanks a lot, I got it.
