### ISSUE TITLE
when i test fashion-data，it shows {"eid": "main"} and stop here

### ISSUE THREAD

**Issue by ziyuwzf** [tengteng95/Pose-Transfer#6]
Total number of parameters: 41358019
-----------------------------------------------
model [TransferModel] was created
WARNING:root:Setting up a new session...
POST /env/main HTTP/1.1
Host: localhost:8097
Accept: */*
Connection: keep-alive
User-Agent: python-requests/2.21.0
Accept-Encoding: gzip, deflate
Content-Length: 15

{"eid": "main"}

**Comment by tengteng95** [comment]
Hi, I do not find any specific errors above and I have no idea why this happens at the moment. What python environment do you use?

**Comment by ziyuwzf** [comment]
我的环境是python3.5+tensorflow1.8.0
最开始我运行test.py提示errno111，socket连接失败，并提示torch没有float32模块
之后我启用了8037的默认端口之后再运行，不会报错，只提显示上面的这个信息

**Comment by tengteng95** [comment]
To run test.py, pytorch is need. Only when calculating the metrics (for example, SSIM), tensorflow is needed.

**Comment by ziyuwzf** [comment]
my pytorch is 0.3.1，and it has been installed

**Comment by tengteng95** [comment]
Do you check the results directory? Are there any generated images? Actually, the socket connection failure does not matter.  You can get rid of the annoying warnings for socket connection by simply add **--display_id 0** at the end of the command line.

**Comment by ziyuwzf** [comment]
there are no images in results directory，i would try your advice

**Comment by ziyuwzf** [comment]
i add  display_id 0,but i shows,my pytorch is 0.3.1
Total number of parameters: 41358019
-----------------------------------------------
model [TransferModel] was created
200
8570
False
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    for i, data in enumerate(dataset):
  File "/media/wzf/disk/project/MyProject/Pose-Transfer-master/data/custom_dataset_data_loader.py", line 40, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/wzf/disk/project/MyProject/Pose-Transfer-master/data/keypoint.py", line 85, in __getitem__
    P1 = self.transform(P1_img)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/functional.py", line 206, in normalize
    mean = torch.tensor(mean, dtype=torch.float32)
AttributeError: module 'torch' has no attribute 'float32'

**Comment by tengteng95** [comment]
I think the problem is the version for torchvision. I use torchvision 0.2.0.

**Comment by ziyuwzf** [comment]
it works! thanks a lot!
