### ISSUE TITLE
The size of tensor a (16) must match the size of tensor b (320) at non-singleton dimension 3

### ISSUE THREAD

**Issue by wduo** [tengteng95/Pose-Transfer#8]
....
Total number of parameters: 41365763

-----------------------------------------------
model [TransferModel] was created
WARNING:root:Setting up a new session...
200
3
False
 process 0/999999 img ..
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    model.test()
  File "/home/ldf/www/Pose-Transfer/models/PATN.py", line 137, in test
    self.fake_p2 = self.netG(G_input)
  File "/home/ldf/www/py35_pytorch031/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ldf/www/Pose-Transfer/models/model_variants.py", line 165, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/ldf/www/py35_pytorch031/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 115, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/ldf/www/py35_pytorch031/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ldf/www/Pose-Transfer/models/model_variants.py", line 148, in forward
    x1, x2, _ = model(x1, x2)
  File "/home/ldf/www/py35_pytorch031/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ldf/www/Pose-Transfer/models/model_variants.py", line 63, in forward
    x1_out = x1_out * att
RuntimeError: The size of tensor a (16) must match the size of tensor b (320) at non-singleton dimension 3

**Comment by wduo** [comment]
Hi @tengteng95 , I use python35(or 27)+pytorch031, and it always give this RuntimeError.
Could you help me?

**Comment by jessemelpolio** [comment]
Could you provide your running commands? From the information you provided, there may be something wrong with your input data or the input channel number settings. You're suggested to check these configurations first.

**Comment by ysl1402** [comment]
Did you solve it? I had the same problem.

**Comment by wangzheliu** [comment]
my running commands:python train.py --dataroot /home/liu@no3/Pose-Transfer/fashion_data/ --name market_PATN --model PATN --lambda_GAN 5 --lambda_A 1 --lambda_B 1 --dataset_mode keypoint --n_layers 3 --norm instance --batchSize 7 --pool_size 0 --resize_or_crop no --gpu_ids 0 --BP_input_nc 18 --no_flip --which_model_netG PATN --niter 500 --niter_decay 200 --checkpoints_dir /home/liu@no3/Pose-Transfer/checkpoints --pairLst /home/liu@no3/Pose-Transfer/fashion_data/fasion-resize-pairs-train.csv --L1_type l1_plus_perL1 --n_layers_D 3 --with_D_PP 1 --with_D_PB 1 --display_id 0





File "/home/liu@no3/Pose-Transfer/models/model_variants.py", line 63, in forward
    x1_out = x1_out * att
RuntimeError: The size of tensor a (64) must match the size of tensor b (44) at non-singleton dimension 3

Do you solve it?I meet same problem

**Comment by jessemelpolio** [comment]
have you already checked out this issue #28 ? The error tells that the size of the pose feature is different from the size of the appearance feature. Maybe you forgot to crop the size of the pose heat maps or the input image to 176 while keeping the other still as 256.

**Comment by wangzheliu** [comment]
> have you already checked out this issue #28 ? The error tells that the size of the pose feature is different from the size of the appearance feature. Maybe you forgot to crop the size of the pose heat maps or the input image to 176 while keeping the other still as 256.

think you very much.how to cropped the images to the size of 256x176,Which program should we run?
