### ISSUE TITLE
[Errno 32] Broken pipe is not going to be frozen to produce an executable.''')

### ISSUE THREAD

**Issue by ronghui19** [tengteng95/Pose-Transfer#81]
Total number of parameters: 41365763
-----------------------------------------------
model [TransferModel] was created
200
12000
False
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Ronghui\Desktop\code\Pose-Transfer-pytorch_v1.0\data\custom_dataset_data_loader.py", line 40, in __iter__
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Ronghui\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Ronghui\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Ronghui\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ronghui\Desktop\code\Pose-Transfer-pytorch_v1.0\test.py", line 33, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Ronghui\Desktop\code\Pose-Transfer-pytorch_v1.0\data\custom_dataset_data_loader.py", line 40, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\Ronghui\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\Ronghui\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
        return _MultiProcessingDataLoaderIter(self)
return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Ronghui\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
  File "C:\Users\Ronghui\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\process.py", line 112, in start
    w.start()
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
    return _default_context.get_context().Process._Popen(process_obj)  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen

  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    return Popen(process_obj)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    reduction.dump(process_obj, to_child)
      File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError:     _check_not_importing_main()
  File "C:\Users\Ronghui\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
[Errno 32] Broken pipe
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by ronghui19** [comment]
Machine: windows10.
when i run the test.py, i came accross such problem. any solution?

**Comment by tengteng95** [comment]
Hi, you'd better to run the model in the linux operating system.
