### ISSUE TITLE
I already cropped image to 256*176,but still get dimension error , please help

### ISSUE THREAD

**Issue by tsbiosky** [tengteng95/Pose-Transfer#84]
python test.py --dataroot ./dataset --name fashion_PATN --model PATN --phase test --dataset_mode keypoint --norm instance --batchSize 1 --resize_or_crop no --gpu_ids 0 --BP_input_nc 18 --no_flip --which_model_netG PATN --checkpoints_dir ./checkpoints/DeepFashion/ --pairLst ./dataset/pair.csv --which_epoch latest --results_dir ./results --display_id 0

Traceback (most recent call last):
  File "test.py", line 39, in <module>
    model.test()
  File "/media/roman/storage/Pose-Transfer/models/PATN.py", line 120, in test
    self.fake_p2 = self.netG(G_input)
  File "/home/roman/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/roman/storage/Pose-Transfer/models/model_variants.py", line 166, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/roman/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 204, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/roman/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/roman/storage/Pose-Transfer/models/model_variants.py", line 149, in forward
    x1, x2, _ = model(x1, x2)
  File "/home/roman/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/roman/storage/Pose-Transfer/models/model_variants.py", line 64, in forward
    x1_out = x1_out * att
RuntimeError: The size of tensor a (64) must match the size of tensor b (16) at non-singleton dimension 3

**Comment by jessemelpolio** [comment]
The reason is the channel dimensions of `x1_out` and `att` are different. Please have a check on your input data and code if there are any possible errors. You can also go into the code and print the size of relevant variables to have a closer check.

**Comment by jessemelpolio** [comment]
From your provided information, I think most probably, the heat map of the pose that you fed is with the incorrect size. Please have a check.

**Comment by akhil451** [comment]
What is the required dimension of the pose heatmap and how to check the same?

**Comment by akhil451** [comment]
Found the issue. The correct Image specs for the model is w-176,h-256

**Comment by akhil451** [comment]
Image input is of the shape w=176,h=256, but unable to perform inference. getting the same error as above.
RuntimeError: The size of tensor a (64) must match the size of tensor b (44) at non-singleton dimension 3
